[build]
  publish = "build" # Директорія з файлами для розгортання (зазвичай "build" або "dist" після компіляції)
  command = "npm run build" # Команда для збірки проекту (залежить від вашого пакетного менеджера)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
